
"use client";

import { useState, memo } from 'react';
import { Button } from '@/components/ui/button';
import { generateMatchRecap } from '@/ai/flows/ai-match-recap-tool';
import { Match } from '@/lib/types';
import { Sparkles, Loader2 } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';

export const MatchRecapButton = memo(function MatchRecapButton({ match }: { match: Match }) {
  const [loading, setLoading] = useState(false);
  const [recap, setRecap] = useState<string | null>(null);
  const [open, setOpen] = useState(false);

  const handleGenerate = async () => {
    if (loading) return;
    setLoading(true);
    setOpen(true);
    try {
      const result = await generateMatchRecap({
        sport: match.sport,
        teamA_name: match.teamA,
        teamA_score: match.scoreA,
        teamB_name: match.teamB,
        teamB_score: match.scoreB,
        keyEvents: match.keyEvents || [],
      });
      setRecap(result.recap);
    } catch (error) {
      setRecap("Recap temporarily unavailable. Please try again soon.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Button 
        variant="ghost" 
        size="sm" 
        className="h-7 text-[10px] font-black uppercase text-primary hover:text-primary hover:bg-primary/5 gap-1.5"
        onClick={handleGenerate}
      >
        <Sparkles className="h-3 w-3" />
        AI Recap
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-[400px] p-0 overflow-hidden border-none shadow-2xl bg-card">
          <DialogHeader className="p-6 bg-primary text-white">
            <DialogTitle className="flex items-center gap-2 text-lg font-black uppercase tracking-tight italic">
              <Sparkles className="h-5 w-5" />
              Paradox Recap
            </DialogTitle>
            <DialogDescription className="text-primary-foreground/80 font-black text-[10px] uppercase tracking-widest">
              {match.teamA} {match.scoreA} - {match.scoreB} {match.teamB}
            </DialogDescription>
          </DialogHeader>
          <div className="p-8 space-y-6">
            {loading ? (
              <div className="flex flex-col items-center justify-center py-10 space-y-4">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="text-[10px] font-black uppercase text-muted-foreground animate-pulse tracking-[0.3em]">Drafting Narrative...</p>
              </div>
            ) : (
              <div className="relative">
                <p className="text-sm md:text-base leading-relaxed font-bold text-foreground italic border-l-4 border-primary/40 pl-5 py-2">
                  "{recap}"
                </p>
                <p className="mt-4 text-[9px] font-bold text-muted-foreground uppercase tracking-widest text-right">
                  Generated by AI Official
                </p>
              </div>
            )}
          </div>
          <div className="px-6 pb-6 flex justify-end">
            <Button variant="ghost" size="sm" className="text-[10px] font-black uppercase h-9 px-6 hover:bg-white/5" onClick={() => setOpen(false)}>Dismiss</Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
});
